spring.application.name=authlab

spring.datasource.url=jdbc:postgresql://localhost:5433/authlab
spring.datasource.username=authlab
spring.datasource.password=authlab

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true